INSERT INTO Quartier (nom_quartier) VALUES
                                        ('Centre-Ville'),
                                        ('Quartier de la Gare'),
                                        ('Saint-Benigne'),
                                        ('Toison d''Or'),
                                        ('Faubourg Raines'),
                                        ('Montmuzard'),
                                        ('Parc Valmy'),
                                        ('Les Bourroches'),
                                        ('Chenôve'),
                                        ('Fontaine d''Ouche');

INSERT INTO Bar (nom, adresse, id_quartier) VALUES
                                                ('Le Zinc', '12 rue de la Liberté', 1),
                                                ('La Bière Folle', '8 avenue Jean Jaurès', 2),
                                                ('Bar de la Gare', '3 place de la Gare', 3),
                                                ('Chez Marcel', '5 rue des Forges', 1),
                                                ('Le Comptoir', '10 boulevard de Maladière', 5),
                                                ('L''Écume', '7 rue du Bourg', 1),
                                                ('Le Chapeau Rouge', '22 rue des Ducs', 4),
                                                ('Le Faubourg', '18 rue Raines', 5),
                                                ('La Mousse', '15 avenue Garibaldi', 4),
                                                ('Le Vieux Pub', '9 place François Rude', 1),
                                                ('Le Marchand de Bières', '20 rue des Godrans', 6),
                                                ('Le Hop''s', '11 avenue Jean Moulin', 7),
                                                ('Le P''tit Zinc', '6 rue de Dijon', 8),
                                                ('La Bière d''Or', '14 rue du Château', 9),
                                                ('Le Baroque', '3 rue Rameau', 10),
                                                ('La Cave à Bières', '7 boulevard Carnot', 2),
                                                ('Le Malt', '19 rue des Bons Enfants', 3),
                                                ('L''Arche', '5 rue Chabot Charny', 6),
                                                ('Le Bock', '8 rue Monge', 7),
                                                ('Le Houblon', '12 rue du Commerce', 8);

INSERT INTO Biere (nom_biere, type_biere, degres_alcool, categorie) VALUES
                                                                        ('Blonde Dijonnaise', 'Blonde', 5.2, 'Artisanale'),
                                                                        ('Rouge de Bourgogne', 'Rousse', 6.0, 'Artisanale'),
                                                                        ('Stout Noir', 'Stout', 7.5, 'Industrielle'),
                                                                        ('IPA Sauvage', 'IPA', 6.8, 'Artisanale'),
                                                                        ('Blanche de l''Ouche', 'Blanche', 5.0, 'Artisanale'),
                                                                        ('Triple Malte', 'Triple', 8.0, 'Artisanale'),
                                                                        ('Pale Ale', 'Pale Ale', 5.5, 'Industrielle'),
                                                                        ('Amber Ale', 'Amber', 5.6, 'Artisanale'),
                                                                        ('Porter de Dijon', 'Porter', 6.2, 'Artisanale'),
                                                                        ('Bière de Noël', 'Spéciale', 6.5, 'Artisanale'),
                                                                        ('IPA Hop', 'IPA', 7.0, 'Industrielle'),
                                                                        ('Blonde de l''Ouche', 'Blonde', 5.3, 'Artisanale'),
                                                                        ('Red Ale', 'Rousse', 5.8, 'Industrielle'),
                                                                        ('Saison Bourroches', 'Saison', 6.0, 'Artisanale'),
                                                                        ('Witbier', 'Blanche', 5.1, 'Artisanale'),
                                                                        ('Bière d''Abbaye', 'Abbaye', 7.2, 'Artisanale'),
                                                                        ('IPA Fontaine', 'IPA', 6.9, 'Artisanale'),
                                                                        ('Blonde Montmuzard', 'Blonde', 5.4, 'Artisanale'),
                                                                        ('Amber Chenôve', 'Amber', 5.7, 'Artisanale'),
                                                                        ('Stout Valmy', 'Stout', 7.4, 'Industrielle'),
                                                                        ('Triple Hop', 'Triple', 8.1, 'Artisanale'),
                                                                        ('Blanche Raines', 'Blanche', 5.0, 'Artisanale'),
                                                                        ('Red Maladière', 'Rousse', 6.1, 'Industrielle'),
                                                                        ('Pale Bourgogne', 'Pale Ale', 5.6, 'Industrielle'),
                                                                        ('Porter du Château', 'Porter', 6.3, 'Artisanale'),
                                                                        ('IPA du Zinc', 'IPA', 6.7, 'Artisanale'),
                                                                        ('Blonde Carnot', 'Blonde', 5.5, 'Artisanale'),
                                                                        ('Saison Dijon', 'Saison', 6.0, 'Artisanale'),
                                                                        ('Amber Hop', 'Amber', 5.9, 'Industrielle'),
                                                                        ('Stout Bock', 'Stout', 7.6, 'Industrielle'),
                                                                        ('Blanche Vieux', 'Blanche', 5.2, 'Artisanale'),
                                                                        ('IPA Malt', 'IPA', 7.1, 'Industrielle'),
                                                                        ('Red Monge', 'Rousse', 6.2, 'Industrielle'),
                                                                        ('Triple Bourgogne', 'Triple', 8.2, 'Artisanale'),
                                                                        ('Blonde Rameau', 'Blonde', 5.3, 'Artisanale'),
                                                                        ('Pale Zinc', 'Pale Ale', 5.7, 'Industrielle'),
                                                                        ('Porter Hop', 'Porter', 6.4, 'Artisanale'),
                                                                        ('IPA Arche', 'IPA', 6.8, 'Artisanale'),
                                                                        ('Blanche Commerce', 'Blanche', 5.1, 'Artisanale'),
                                                                        ('Golden Ale', 'Blonde', 5.2, 'Artisanale'),
                                                                        ('Honey Stout', 'Stout', 6.8, 'Artisanale'),
                                                                        ('Citra IPA', 'IPA', 6.5, 'Artisanale'),
                                                                        ('Maple Amber', 'Amber', 5.9, 'Artisanale'),
                                                                        ('Winter Saison', 'Saison', 6.3, 'Artisanale'),
                                                                        ('Cherry Blonde', 'Blonde', 5.1, 'Artisanale'),
                                                                        ('Blonde Hop', 'Blonde', 5.3, 'Artisanale'),
                                                                        ('Red Bourbon', 'Rousse', 6.0, 'Artisanale');

INSERT INTO Prix (id_bar, id_biere, prix) VALUES
                                              (1,1,5.5),(1,2,6.0),(1,3,6.2),(1,4,6.5),(1,5,5.0),(1,6,7.0),(1,7,5.5),(1,8,5.6),(1,9,6.0),(1,10,6.5),
                                              (2,1,5.3),(2,2,6.1),(2,3,6.4),(2,4,6.7),(2,5,5.2),(2,6,8.0),(2,7,5.5),(2,11,7.0),(2,12,5.3),(2,13,5.8),
                                              (3,1,5.2),(3,14,6.0),(3,15,5.1),(3,16,7.2),(3,17,6.9),(3,18,5.4),(3,19,5.7),(3,20,7.4),(3,21,5.0),(3,22,6.1),
                                              (4,1,5.4),(4,2,6.2),(4,3,6.3),(4,4,6.7),(4,5,5.1),(4,6,8.0),(4,7,5.5),(4,23,5.6),(4,24,5.9),(4,25,6.2),
                                              (5,1,5.5),(5,2,6.1),(5,3,6.4),(5,4,6.7),(5,5,5.1),(5,6,8.0),(5,7,5.5),(5,26,6.0),(5,27,5.8),(5,28,6.3),
                                              (6,1,5.6),(6,2,6.0),(6,3,5.9),(6,4,6.1),(6,5,6.3),(6,6,7.0),(6,7,5.2),(6,29,5.5),(6,30,6.0),(6,31,6.2),
                                              (7,1,5.3),(7,2,6.2),(7,3,5.8),(7,4,6.0),(7,5,5.1),(7,6,7.1),(7,7,6.8),(7,32,5.5),(7,33,6.1),(7,34,6.3),
                                              (8,1,5.5),(8,2,6.0),(8,3,6.3),(8,4,6.6),(8,5,5.2),(8,6,8.1),(8,7,5.5),(8,35,6.0),(8,36,5.8),(8,37,6.4),
                                              (9,1,5.6),(9,2,6.1),(9,3,5.9),(9,4,6.2),(9,5,6.4),(9,6,7.1),(9,7,5.3),(9,38,5.5),(9,39,6.0),(9,40,5.9),
                                              (10,1,5.4),(10,2,6.0),(10,3,6.5),(10,4,6.8),(10,5,5.1),(10,6,8.0),(10,7,5.5),(10,41,5.6),(10,42,6.2),(10,43,5.8),
                                              (11,1,5.5),(11,2,6.1),(11,3,6.3),(11,4,6.7),(11,5,5.2),(11,6,5.9),(11,7,6.0),(11,44,6.3),(11,45,5.8),(11,46,6.1),
                                              (12,15,5.7),(12,16,6.3),(12,17,7.0),
                                              (13,18,5.4),(13,19,5.8),(13,20,6.2),
                                              (14,21,5.6),(14,22,6.1),(14,23,5.9),
                                              (15,24,6.0),(15,25,5.5),(15,26,6.4),
                                              (16,27,5.8),(16,28,6.2),(16,29,5.9),
                                              (17,30,6.1),(17,31,5.7),(17,32,6.3),
                                              (18,33,5.5),(18,34,6.0),(18,35,6.2),
                                              (19,36,5.8),(19,37,6.1),(19,38,5.9),
                                              (20,39,6.3),(20,40,5.6),(20,41,6.0),
                                              (20,42,5.8),(20,43,6.2),(20,44,5.9),
                                              (1,41,6.1),(2,42,5.9),(3,43,6.0),(4,44,6.2),(5,45,5.7),
                                              (6,46,6.1),(7,41,5.8),(8,42,6.0),(9,43,5.9),(10,44,6.2);
